# ==========================================
# 1. Server & File Upload Configurations
# ==========================================
server.port=8080
# Increase upload limits for PDF documents
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# ==========================================
# 2. Blockchain / Hardhat Configuration
# ==========================================
# Connects to your local Hardhat node
blockchain.node.url=http://127.0.0.1:8545
# The exact address where you deployed DocumentRegistry earlier
blockchain.contract.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
# Hardhat Account #0 Private Key (This account is the contract owner)
# WARNING: Never use this specific key on a public testnet/mainnet!
blockchain.wallet.private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# ==========================================
# 3. Pinata IPFS Configuration
# ==========================================
pinata.api.url=https://api.pinata.cloud
# We will replace this placeholder with your real token
pinata.jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI1YjIxYjQ2YS04ODg2LTQ2MTItYjZkZS1hMWJkNzhlYTU1YzQiLCJlbWFpbCI6ImthaWxhc25hdGhrMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiMzA5MDhjYzhhMWE5NWI3ZDI3ZWUiLCJzY29wZWRLZXlTZWNyZXQiOiIwYjM3MDg4MmQ4ODg2YjIzMjQ2YmFkMTJkOTJiOWRiODM2MTQzMThmMjhhMzgzOWQwZDhiYTJhNDRlYjRlYWQ3IiwiZXhwIjoxODE2NTkwMTE2fQ.CFxM5bUYimkbQ2uLgaJY46gadxvnrwely_CIbDaGRX0